name: compound_scanner
description: Compound Scanner
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  image: ^4.0.17
  image_picker: ^0.8.9
  pytorch_lite: ^2.0.5
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  # tflite_flutter: ^0.10.1
  fluttertoast: ^8.2.2
  dio: ^5.2.1+1
  # tflite_flutter_helper_plus: ^0.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/img/icon.png"
  android: true
  # for some reason the default foreground generation didnt work for android,
  # so I manually pasted mipmaps generated on https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
  # adaptive_icon_foreground: "assets/img/foreground.png"
  adaptive_icon_background: "#171717"

flutter:
  uses-material-design: true

  # assets:
  #   # - assets/models/encoder.tflite
  #   # - assets/models/decoder.tflite
  #   # - assets/models/isg.tflite
  #   - assets/models/decimer.tflite
  #   # - assets/models/transformer_decimer.tflite
